# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ground-x/go-gxplatform
    steps:
      - checkout
      - run: make

  dockernize:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ground-x/go-gxplatform
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Install awscli"
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/gxp/client-go:latest -t $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/gxp/client-go:$CIRCLE_SHA1 .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/gxp/client-go:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/gxp/client-go:$CIRCLE_SHA1
workflows:
  version: 2
  build_and_dockernize:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - dockernize:
          filters:
            branches:
              only:
                - master
   
